### PR TITLE
Fix generate map method when values contains `$` symbol

### LINKED ISSUE #147: Can't use AOT with config URLs that contain `$`
### Expected Behavior

Expect that any legal YAML config that is usable with Micronaut also to be usable with AOT

I have the following URL intercept map:
```yaml
micronaut:
  security:
    intercept-url-map:
      # (other URLs omitted for brevity)
      -
        pattern: /v1/odata/$metadata
        http-method: GET
```

When I run the regular non-AOT build, it works fine and handles the URL with the dollar sign present.

### Actual Behaviour

When I run the regular non-AOT build, it works fine and handles the URL with the dollar sign present. With the AOT build active and YAML->Java compilation turned off, things also work fine. With YAML->Java enabled, I get:

```
Caused by: java.lang.IllegalArgumentException: index 1 for '$m' not in range (received 0 arguments)
        at com.squareup.javapoet.Util.checkArgument(Util.java:53)
        at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:287)
        at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:402)
        at com.squareup.javapoet.MethodSpec$Builder.addStatement(MethodSpec.java:525)
        at io.micronaut.aot.core.codegen.MapGenerator.generateMapMethod(MapGenerator.java:121)
        at io.micronaut.aot.core.codegen.MapGenerator.convertValueToSource(MapGenerator.java:63)
        at io.micronaut.aot.core.codegen.MapGenerator.generateListMethod(MapGenerator.java:100)
        at io.micronaut.aot.core.codegen.MapGenerator.convertValueToSource(MapGenerator.java:61)
        at io.micronaut.aot.core.codegen.MapGenerator.generateMap(MapGenerator.java:44)
        at io.micronaut.aot.std.sourcegen.MapPropertySourceGenerator.generate(MapPropertySourceGenerator.java:77)
        at io.micronaut.aot.core.codegen.AbstractSingleClassFileGenerator.generate(AbstractSingleClassFileGenerator.java:35)
        at io.micronaut.aot.std.sourcegen.YamlPropertySourceGenerator.createMapProperty(YamlPropertySourceGenerator.java:75)
        at io.micronaut.aot.std.sourcegen.YamlPropertySourceGenerator.generate(YamlPropertySourceGenerator.java:58)
        at io.micronaut.aot.std.sourcegen.AbstractStaticServiceLoaderSourceGenerator.generate(AbstractStaticServiceLoaderSourceGenerator.java:106)
        at io.micronaut.aot.core.codegen.ApplicationContextConfigurerGenerator.generate(ApplicationContextConfigurerGenerator.java:66)
        at io.micronaut.aot.MicronautAotOptimizer$Runner.execute(MicronautAotOptimizer.java:343)
        at io.micronaut.aot.MicronautAotOptimizer.execute(MicronautAotOptimizer.java:202)
        ... 15 more
```

It appears to be evaluating this `$` as a format character. The following mitigations appeared to do nothing:
- Single-quoting the string
- Double-quoting the string
- Escaping (single `\`) before the `$`

### Steps To Reproduce

1. With Micronaut AOT and YAML->Java enabled...
2. Add the above intercept URL config, or just a URL containing a `$`
3. Run the build

### Environment Information

- Operating system: macOS Ventura
- JDK Version: 17

### Example Application

_No response_

### Version

3.7.3

### PR DESCRIPTION
**Pull request by altro3**
Fixed #147

### CODE REVIEW

**Comment by altro3** [comment]
@melix Hi! This is th same proble as here #174, but for map methods

**Comment by altro3** [comment]
@melix Could youu tell when you planning release these fixes? Want to use yaml optimizer, but can't because of these bugs :-(

**Comment by melix** [comment]
I can perform a release this week.

**Comment by melix** [comment]
@altro3 would you mind fixing the failing test (expectation is wrong after merging your other PR)

**Comment by altro3** [comment]
@melix yeah, sure

**Comment by altro3** [comment]
@melix done

**Pull request merged**
