### PR TITLE
AOT to Core 4.0.0-RC3

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by timyates** [comment]
@melix can you see what's going on here?

[In this test](https://github.com/micronaut-projects/micronaut-aot/blob/ded7dfb3d96ee4af6135ae343c831e14987871c1/aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/PublishersSourceGeneratorTest.groovy)

We're expecting (with whitespace added for readability):

```
    return new PublishersOptimizations(
        Arrays.asList(
            CompletableFuturePublisher.class,
            Publishers.JustPublisher.class,
            Completable.class
        ),
        Arrays.asList(
            CompletableFuturePublisher.class,
            Publishers.JustPublisher.class
        ), Arrays.asList(Completable.class));
```

But we're now getting:

```diff
    return new PublishersOptimizations(
        Arrays.asList(
            CompletableFuturePublisher.class,
            Publishers.JustPublisher.class,
+            Publishers.JustThrowPublisher.class, 
            Completable.class
        ),
        Arrays.asList(
            CompletableFuturePublisher.class,
-            Publishers.JustPublisher.class
+            Publishers.JustPublisher.class,
+            Publishers.JustThrowPublisher.class
        ), Arrays.asList(Completable.class));
```

So `JustThrowPublisher` has been added to the list.  However, this class is private in core

https://github.com/micronaut-projects/micronaut-core/blob/741dc500e6e41ae417f5350dcd3be8a61e9e6788/core-reactive/src/main/java/io/micronaut/core/async/publisher/Publishers.java#L624-L623

And I cannot see that it's changed recently 🤔

**Comment by melix** [comment]
Indeed this looks like a breaking change wrt AOT. @graemerocher can we make `JustThrowPublisher` public? Otherwise I think we'll have to remove this optimization, since it requires the classes to be accessible.

**Comment by melix** [comment]
I think the test needs adjusting now, I'll take a look.

**Comment by sdelamo** [comment]
`:micronaut-aot-std-optimizers:test` fails with: 

https://ge.micronaut.io/s/s34oza6hd34n2

CleanShot 2023-06-21 at 07 42 39@2x

Can you check it out @melix ?

**Pull request merged**
